const documentos = {
    "Memorando Nro. ENAMI-GDM-2026-0059-MEM": {
        "tipo": "MEMORANDO",
        "id": "Memorando Nro. ENAMI-GDM-2026-0059-MEM",
        "fecha": "Quito, D.M., 11 de marzo de 2026",
        "para": "<b>Sra. Abg. Gabriela Sibia Jauregui Moran</b><br>Gerente Negocios Mineros",
        "de": "<b>Documento firmado electr\u00f3nicamente</b><br>Mgs. Diego Andr\u00e9s Rueda Albuja",
        "asunto": "N/D",
        "copias": [
            "Sr. Mgs. Galo Andr\u00e9s Garc\u00eda Medina",
            "Gerente General, Subrogante",
            "Sr. Mgs. Lenin Vladimir Ochoa Ochoa",
            "Subgerente Jur\u00eddico",
            "Sr. Ing. Marlon Oswaldo Lara Mier",
            "Director Ambiental y Social (E)",
            "Sr. Ing. Iv\u00e1n Arturo Delgado Quingalombo",
            "Director T\u00e9cnico de Operaciones Mineras (E)",
            "Sr. Mgs. William Fernando Mu\u00f1oz Ruiz",
            "Analista 1 - Social",
            "Sr. Lcdo. Steven Alexander Guaranda Bazurto",
            "Asistente Administrativo",
            "",
            "Direcci\u00f3n: Av. 6 de Diciembre N31-110 y Whymper, Edificio Torres Tenerife",
            "C\u00f3digo Postal: 170517 / Quito Ecuador. Tel\u00e9fono: \u00b1593 2 395 3000",
            "www.enamiep.gob.ec",
            "* Documento firmado electr\u00f3nicamente por Quipux"
        ]
    },
    "Oficio Nro. ENAMI-SPGE-2026-0005-OFC": {
        "tipo": "OFICIO",
        "id": "Oficio Nro. ENAMI-SPGE-2026-0005-OFC",
        "fecha": "Quito, D.M., 11 de marzo de 2026",
        "para": "N/D",
        "de": "<b>Documento firmado electr\u00f3nicamente</b><br>Mgs. Xavier Floresmilo Bola\u00f1os Cuzco",
        "asunto": "Respuesta a la solicitud de informe t\u00e9cnico para actividades priorizadas - Programa de Gesti\u00f3n Sostenible e Infraestructura Asociada Se\u00f1or Mag\u00edster Jorge Roberto Solano Mera",
        "copias": [
            "Se\u00f1ora M\u00e1ster",
            "Ms. In\u00e9s Mar\u00eda Manzano D\u00edaz",
            "Ministra de Ambiente y Energ\u00eda",
            "MINISTERIO DE AMBIENTE Y ENERG\u00cdA",
            "Se\u00f1or Mag\u00edster",
            "Guillermo Iv\u00e1n Flores Caama\u00f1o",
            "Viceministro de Minas",
            "MINISTERIO DE AMBIENTE Y ENERG\u00cdA",
            "Se\u00f1or Mag\u00edster",
            "Galo Andr\u00e9s Garc\u00eda Medina",
            "Gerente General, Subrogante",
            "Se\u00f1or Mag\u00edster",
            "Diego Andr\u00e9s Rueda Albuja",
            "Gerente de Gesti\u00f3n y Desarrollo Minero",
            "Se\u00f1or Ingeniero",
            "Francisco Javier Gudi\u00f1o Lara",
            "Analista 1 - Procesos",
            "",
            "Direcci\u00f3n: Av. 6 de Diciembre N31-110 y Whymper, Edificio Torres Tenerife",
            "C\u00f3digo Postal: 170517 / Quito Ecuador. Tel\u00e9fono: \u00b1593 2 395 3000",
            "www.enamiep.gob.ec",
            "* Documento firmado electr\u00f3nicamente por Quipux",
            "DEL ECUADOR",
            "Oficio Nro. ENAMI-SPGE-2026-0005-OFC",
            "Quito, D.M., 11 de marzo de 2026",
            "",
            "Direcci\u00f3n: Av. 6 de Diciembre N31-110 y Whymper, Edificio Torres Tenerife",
            "C\u00f3digo Postal: 170517 / Quito Ecuador. Tel\u00e9fono: \u00b1593 2 395 3000",
            "www.enamiep.gob.ec",
            "* Documento firmado electr\u00f3nicamente por Quipux"
        ]
    },
    "Memorando Nro. ENAMI-SPGE-2026-0033-MEM": {
        "tipo": "MEMORANDO",
        "id": "Memorando Nro. ENAMI-SPGE-2026-0033-MEM",
        "fecha": "Quito, D.M., 12 de marzo de 2026",
        "para": "<b>Sr. Mgs. Galo Andr\u00e9s Garc\u00eda Medina</b><br>Gerente General, Subrogante",
        "de": "<b>Empresa Nacional Minera</b><br>Direcci\u00f3n: Av. 6 de Diciembre N31-110 y Whymper, Edificio Torres Tenerife",
        "asunto": "N/D",
        "copias": [
            "Sr. Mgs. Diego Andr\u00e9s Rueda Albuja",
            "Gerente de Gesti\u00f3n y Desarrollo Minero",
            "Sra. Mgs. Viviana del Carmen Almeida Moreno",
            "Subgerente Administrativa Financiera",
            "Sr. Ing. Francisco Javier Gudi\u00f1o Lara",
            "Analista 1 - Procesos",
            "",
            "Direcci\u00f3n: Av. 6 de Diciembre N31-110 y Whymper, Edificio Torres Tenerife",
            "C\u00f3digo Postal: 170517 / Quito Ecuador. Tel\u00e9fono: \u00b1593 2 395 3000",
            "www.enamiep.gob.ec",
            "* Documento firmado electr\u00f3nicamente por Quipux"
        ]
    },
    "Memorando Nro. ENAMI-GDM-2026-0060-MEM": {
        "tipo": "MEMORANDO",
        "id": "Memorando Nro. ENAMI-GDM-2026-0060-MEM",
        "fecha": "Quito, D.M., 13 de marzo de 2026",
        "para": "<b>Sr. Mgs. Galo Andr\u00e9s Garc\u00eda Medina</b><br>Gerente General, Subrogante",
        "de": "<b>Documento firmado electr\u00f3nicamente</b><br>Mgs. Diego Andr\u00e9s Rueda Albuja",
        "asunto": "N/D",
        "copias": [
            "Sra. Soc. Jessica Jacqueline Macas Machuca",
            "Analista 1 - Social",
            "Sr. Lcdo. Steven Alexander Guaranda Bazurto",
            "Asistente Administrativo",
            "",
            "Direcci\u00f3n: Av. 6 de Diciembre N31-110 y Whymper, Edificio Torres Tenerife",
            "C\u00f3digo Postal: 170517 / Quito Ecuador. Tel\u00e9fono: \u00b1593 2 395 3000",
            "www.enamiep.gob.ec",
            "* Documento firmado electr\u00f3nicamente por Quipux"
        ]
    }
};